spring:
  application:
    name: gather
  profiles:
    active: local
  config:
    import: optional:application-secret.yml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
