CREATE TABLE categories (
    id   BIGINT      NOT NULL AUTO_INCREMENT,
    code VARCHAR(30) NOT NULL COMMENT '봉사분야 코드(enum: ENVIRONMENT/EDUCATION/CULTURE/COMMUNITY/WELFARE/OVERSEAS)',
    name VARCHAR(50) NOT NULL COMMENT '봉사분야명',
    PRIMARY KEY (id),
    CONSTRAINT uk_category_code UNIQUE (code)
);
