CREATE TABLE volunteer_posting (
    id                BIGINT       NOT NULL AUTO_INCREMENT,
    ext_id            VARCHAR(255) NULL COMMENT '1365 봉사참여정보서비스 원본 공고 ID',
    title             VARCHAR(255) NOT NULL,
    status            ENUM ('CLOSED', 'COMPLETED', 'RECRUITING') NOT NULL,
    content           LONGTEXT     NULL,
    recruit_org       VARCHAR(255) NULL,
    register_org      VARCHAR(255) NULL,
    activity_date     DATE         NOT NULL,
    act_start_date    DATE         NULL,
    act_end_date      DATE         NULL,
    act_start_time    VARCHAR(255) NULL,
    act_end_time      VARCHAR(255) NULL,
    notice_start_date DATE         NULL,
    notice_end_date   DATE         NULL,
    act_wkdy          VARCHAR(255) NULL,
    recruit_count     INT          NULL,
    applicant_count   INT          NULL,
    is_adult          BIT(1)       NULL,
    is_teen           BIT(1)       NULL,
    is_group          BIT(1)       NULL,
    is_active         BIT(1)       NULL COMMENT '해당 공고의 봉사 실행 날짜가 지난 공고는 false로',
    act_place         VARCHAR(255) NULL,
    post_address      VARCHAR(255) NULL,
    manager_name      VARCHAR(255) NULL,
    manager_tel       VARCHAR(255) NULL,
    manager_fax       VARCHAR(255) NULL,
    manager_email     VARCHAR(255) NULL,
    manager_address   VARCHAR(255) NULL,
    latitude          DECIMAL(10, 7) NULL,
    longitude         DECIMAL(11, 7) NULL,
    created_at        DATETIME(6)  NULL,
    updated_at        DATETIME(6)  NULL,
    region_id         BIGINT       NULL COMMENT 'region 테이블(posting 도메인 소유) 참조. 도메인 간 결합을 피하기 위해 FK 없이 ID만 보관',
    category_id       BIGINT       NOT NULL COMMENT 'category 테이블(meeting 도메인 소유) 참조. 같은 이유로 FK 없이 ID만 보관',
    PRIMARY KEY (id),
    CONSTRAINT uk_volunteer_posting_ext_id UNIQUE (ext_id)
);
